project:
  type: website

website:
  site-url: "https://haymanot.netlify.app"
  title: "Haymanot"
  description: "Welcome to my website"
  navbar:
    left:
      - pages/about.qmd
      - pages/lecture.qmd
      - pages/exprience.qmd
      - pages/puplications.qmd
      - pages/presentations.qmd
      
      
    right:
      - text: blog
        href: https://himi-be-my.blogspot.com/
      - icon: github
        href: https://github.com/HaymanotB
  page-footer: 
    left:  <span class="faux-block">&#169; 2024 Haymanot Berehan  CC BY-SA 4.0</span>
    border: true
  # repo-url: "https://github.com/HaymanotB/website/"
  # repo-actions: [issue]
  open-graph: true
format:
  html:
    # page-layout: full
    theme: theme.scss
# Other nice themes: lumen, sandstone (with dark banner) or flatly & darkly


